### ISSUE TITLE
Server side rendered vs useQuery hook

### ISSUE THREAD

**Issue by shopkins131** [thendra/TreasuryNext#1]
https://github.com/thendra/TreasuryNext/blob/1a0f85f60bb7bc0a320e564191ce59bcc03c4a9d/pages/items.tsx#L34

Looking at the Items page. Wouldn't we want to try and server side render these items? Rather than the front end doing the work in a useQuery hook?

**Comment by shopkins131** [comment]
Below is a code snippet from my Titan Travel site. I think you want to do something similar to this but in a "getServerSideProps"

I used this repo as a starter: https://github.com/vercel/next.js/tree/canary/examples/with-typescript-graphql 

`export const getStaticPaths: GetStaticPaths = async () => {
  const apolloClient = initializeApollo();
  const res = await apolloClient.query({
    query: productPathsQuery,
  });

  const products: Product[] = get(res, "data.ProductItems.items");

  if (!products) throw new Error("Problem fetching Product Urls");

  const paths: any[] = products.map((product) => `/${product.slug}`);

  return {
    paths,
    fallback: false,
  };
};`

**Comment by thendra** [comment]
> https://github.com/thendra/TreasuryNext/blob/1a0f85f60bb7bc0a320e564191ce59bcc03c4a9d/pages/items.tsx#L34
> 
> Looking at the Items page. Wouldn't we want to try and server side render these items? Rather than the front end doing the work in a useQuery hook?

This page is server side rendered as it's wrapped in my withApollo HOC which enables us to use the useQuery hook to fetch data on the client side whilst statically rendering the rest of the page 👌
